#!/usr/bin/env python3

import argparse
import serial
from time import sleep 


parser = argparse.ArgumentParser(description='Read strings over USB')
parser.add_argument('--port', required=False,  help='USB port to use, defaults to /dev/ttyUSB0')
parser.add_argument('--wait', required=False, default=0, type=int, help='Second to wait after opening the connection. Useful for devices like arduino that are rest when the serial connection is opened.')
parser.add_argument('--baud', required=False, default=9600, type=int, help='Desired baud rate. Defaults to 9600.')

args = parser.parse_args()

port = vars(args)["port"]
wait = vars(args)["wait"]
baud = vars(args)["baud"]

#port defaults to /dev/ttyUSB0
#TODO: do a query and pick a sensible and non-platform specific default
if port is None or port == "":
	port = "/dev/ttyUSB0"

ser = serial.serial_for_url(port, do_not_open=True)
ser.baudrate = baud
print(baud)
ser.open()

if wait > 0:
	sleep(wait)

while True:
     cc=str(ser.readline())
     print(cc[2:][:-5])



  
