#!/usr/bin/env python3

import argparse
import serial

parser = argparse.ArgumentParser(description='Send strings over USB')
parser.add_argument('--string', required=True, help='The string to send')
parser.add_argument('--port', required=False, help='USB port to use, defaults to /dev/ttyUSB0')
args = parser.parse_args()

cmd = vars(args)["string"]
port = vars(args)["port"]

if port is None or port == "":
	port = "/dev/ttyUSB0"
print(port)

ser = serial.Serial(port,9600)
ser.flushInput()


if cmd is not None:
	ser.write(str.encode(cmd))




